name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Output Environment Variables
        run: |
          echo "BASE_URL_PROD=${secrets.BASE_URL_PROD}"
          echo "API_KEY_PROD=${secrets.API_KEY_PROD}"
          echo "BASE_URL_DEV=${secrets.BASE_URL_DEV}"
          echo "API_KEY_DEV=${secrets.API_KEY_DEV}"
          echo "ENC_KEY=${secrets.ENC_KEY}"
          echo "USER_LIST=${secrets.USER_LIST}"

      - name: Build and push Docker image
        env: 
          BASE_URL_PROD : ${{ secrets.BASE_URL_PROD }}
          API_KEY_PROD : ${{ secrets.API_KEY_PROD }}
          BASE_URL_DEV : ${{ secrets.BASE_URL_DEV }}
          API_KEY_DEV : ${{ secrets.API_KEY_DEV }}
          ENC_KEY : ${{ secrets.ENC_KEY }}
          USER_LIST : ${{ secrets.USER_LIST }}
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/modigitalsign:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/modigitalsign:${{ github.sha }}