name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Check if Docker image exists on Docker Hub
        run: |
          # response=`curl -s https://hub.docker.com/v2/repositories/modigitalsign/`
          # echo "HTTP Status Code: $response"

          image_exist = docker manifest inspect gifarz06/modigitalsign:latest

          response=$(echo "$image_exist" | grep -q "no such manifest:")
          echo "response : $response"

          # if [ $response -eq 1 ]; then
          #   echo "IMAGE_EXISTS=true" >> $GITHUB_ENV
          #   echo "IMAGE_EXISTS: true"
          # else
          #   echo "IMAGE_EXISTS=false" >> $GITHUB_ENV
          #   echo "IMAGE_EXISTS: false"
          # fi

          if echo "$image_exist" | grep -q "no such manifest:"; then
            echo "IMAGE_EXISTS=false" >> $GITHUB_ENV
            echo "IMAGE_EXISTS: false"
          else
            echo "IMAGE_EXISTS=true" >> $GITHUB_ENV
            echo "IMAGE_EXISTS: true"
          fi

      - name: Log in to Docker Hub (if using a private registry)
        if: env.IMAGE_EXISTS == 'false'
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        if: env.IMAGE_EXISTS == 'false'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/modigitalsign:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/modigitalsign:latest

      - name: Stop and remove containers using the old image
        run: |
          docker ps -a | grep modigitalsign | awk '{print $1}' | xargs -I {} docker stop {}
          docker ps -a | grep modigitalsign | awk '{print $1}' | xargs -I {} docker rm {}

      - name: Run containers with the updated image
        run: docker run -d --name modigitalsign ${{ secrets.DOCKER_USERNAME }}/modigitalsign:latest