name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: SSH into server behind F5
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.F5_HOST }}
          username: ${{ secrets.F5_USERNAME }}
          password: ${{ secrets.F5_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}

      # - name: Check if Docker image exists on the server
      #   run: |
      #     ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} -p ${{ secrets.SERVER_PORT }} "docker image inspect mo-digitalsign:1.0 > /dev/null 2>&1 || echo 'Image does not exist'"

      #   continue-on-error: true

      # - name: Pull or build and run Docker image on the server
      #   run: |
      #     ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} -p ${{ secrets.SERVER_PORT }} "docker pull mo-digitalsign:1.0 || (docker build -t mo-digitalsign:1.0 . && docker run -d --name mo-digitalsign mo-digitalsign:1.0)"

      # - name: Remove temporary Docker image
      #   run: |
      #     ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} -p ${{ secrets.SERVER_PORT }} "docker rmi mo-digitalsign:1.0"