name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Build and test
      run: |
        docker build -t mo-digitalsign:1.0 .

        # Stop the existing container (ignore errors if it doesn't exist)
        docker stop mo-digitalsign || true

        # Remove the existing container (ignore errors if it doesn't exist)
        docker rm mo-digitalsign || true

        docker run --name mo-digitalsign -p 3030:3000 -d mo-digitalsign:1.0