name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test
      run: |
        docker build -t mo-nuxt:1.0 .
        docker run mo-nuxt:1.0 npm test
